""" Template for interface between physics engine and muscle system. """

cdef class PhysicsInterface(object):
    """Interface between physics engine and muscle model
    """
    
    def __init__(self, lmtu, force, stim, engine='NONE'):
        super(PhysicsInterface, self).__init__()
        self.engine = engine
        self.lmtu = lmtu
        self.force = force
        self.stim = stim

    #################### PY-FUNCTIONS ####################
    def add_waypoints(waypoints):
        """ Add new attachment point. 
        Parameters
        ----------
        attachment_points: <dict>
            Dictionary containing link names and attachment points
        """
        pass

    def py_compute_muscle_length(self):
        self.c_compute_muscle_length()
        
    #################### C-FUNCTIONS ####################
    cdef void c_compute_muscle_length(self):
        """ Compute the muscle length based on the physics simulator. """
        pass

    cdef void c_apply_muscle_forces(self):
        """ Apply the forces generated by the muscle onto the physical links. """
        pass

    cdef void c_show_muscle(self, bint VISUALIZATION=True):
        """ Muscle Visualization """
        pass
